name: Issue Template
description: Track an issue
title: "[Issue] <title>"
labels: [help wanted, good first issue]
assignees:
  - nicolas-mark
body:
- type: checkboxes
  attributes:
    label: Does an issue already exist for this?
    description: Please verify an issue does not already exist for this.
    options:
    - label: I have done my due diligence.
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations: 
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations: 
    required: false
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. Encounter error
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Arch 2021.01.01
        - **cryptsetup**: 2.4.0
    value: |
        - OS:
        - cryptsetup:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything more?
    description: |
      Links? References? Anything providing more context regarding the issue.

      Tip: You may attach images or log files.
  validations:
    required: false
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to the [Code of Conduct](../../docs/CODE_OF_CONDUCT.md)